theme: jekyll-theme-cayman
I am a Data Scientist with five years experience in statistical modeling, predictive modeling, data mining, data visualization
I am skilled in python programming language, SQL, PHP, Git, Github, MYSQL, Bash, Django Framework, and Laravel.
