theme: jekyll-theme-cayman
<h1>I am a Data Scientist with five years experience in statistical modeling, predictive modeling, data mining, data visualization</h1>
<p>I am skilled in python programming language, SQL, PHP, Git, Github, MYSQL, Bash, Django Framework, and Laravel.
